workers_dev = true
name = "openai-compat"
compatibility_date = "2024-11-18"
# main = "./workers/app.ts"
main = "./build/server/index.js"
assets = { directory = "./build/client/" }

[vars]
VALUE_FROM_CLOUDFLARE = "Hello from Cloudflare"
