// Generated by Wrangler by running `wrangler types` (hash: 6010579e7036b8e6b05c519a8fe71413)
// Runtime types generated with workerd@1.20250409.0 2025-04-01 nodejs_compat
declare namespace Cloudflare {
  interface Env {
    AuthKV: KVNamespace;
  }
}
interface Env extends Cloudflare.Env {}
